import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Header from '@/components/Header';
import SmoothScroll from '@/components/SmoothScroll';
import GradualBlurMemo from '@/components/ui/gradual-blur';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className='flex flex-col min-h-300 bg-slate-950'>
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
        <GradualBlurMemo
          target='page'
          position='bottom'
          height='7rem'
          strength={5}
          divCount={2}
          curve='bezier'
          exponential
          opacity={0.9}
        />
      </body>
    </html>
  );
}
